services:

  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pass
    restart: always
    ports:
      - 5432:5432

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
    restart: always

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    depends_on: 
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always